### ISSUE TITLE
Need more warning before starting run 0xffffffff

### ISSUE THREAD

**Issue by boardhead** [snoplus/orca#168]
ORCA currently gets the new run number from the detector database when a run is started, but if the database operation fails a run will be started with number 0xffffffff, which will result in (effectively) a loss of data.  ORCA should probably post an app-modal dialog before starting the run if it was operator-initiated, but what to do on auto-started runs?

**Comment by boardhead** [comment]
Or possibly just abort a run start if the database is not available.  This might be a better solution.

**Comment by fbdescamps** [comment]
I think we should still be able to start a run when the database is not available so that we have access to high-level monitoring like xsnoed even if, like you say, the data will not be useable. A dialog pop-up sounds like a good idea. For the auto-started runs, can we have the dialog and/or issue an alarm?

**Comment by mastbaum** [comment]
Closed by #486
